import { PrismaPg } from "@prisma/adapter-pg";
import { Difficulty, type Prisma, PrismaClient, SessionStatus } from "../src/generated/prisma/client.js";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is missing");
}

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({
  adapter,
});

const getRandomExp = () => Math.floor(Math.random() * 20001);

// generated by gemini
export async function main() {
  console.log("🌱 Starting database seed...");

  await prisma.user.deleteMany();
  console.log("🧹 Cleared existing data.");

  const rawUsers = [
    {
      email: "alice@example.com",
      username: "alice_wonder",
      password: "password123",
      bio: "Trivia enthusiast and science lover.",
      sessions: [
        {
          totalQuestions: 3,
          score: 2,
          status: "COMPLETED",
          category: "Science",
          difficulty: "EASY",
          results: [
            { questionText: "What is H2O?", correctAnswer: "Water", userAnswer: "Water", isCorrect: true },
            { questionText: "What is the powerhouse of the cell?", correctAnswer: "Mitochondria", userAnswer: "Nucleus", isCorrect: false },
            { questionText: "What planet is closest to the sun?", correctAnswer: "Mercury", userAnswer: "Mercury", isCorrect: true },
          ],
        },
        {
          totalQuestions: 5,
          score: 2,
          status: "IN_PROGRESS",
          category: "Science",
          difficulty: "MEDIUM",
          results: [
            { questionText: "What is the hardest natural substance?", correctAnswer: "Diamond", userAnswer: "Diamond", isCorrect: true },
            { questionText: "What is the symbol for Gold?", correctAnswer: "Au", userAnswer: "Au", isCorrect: true },
            { questionText: "How many bones in the human body?", correctAnswer: "206", userAnswer: null, isCorrect: false },
            { questionText: "What is the speed of light?", correctAnswer: "299,792 km/s", userAnswer: null, isCorrect: false },
            { questionText: "Who developed the theory of relativity?", correctAnswer: "Albert Einstein", userAnswer: null, isCorrect: false },
          ],
        },
      ],
    },
    {
      email: "bob@example.com",
      username: "bob_builder",
      password: "securepassword456",
      bio: "Just here to learn history.",
      sessions: [
        {
          totalQuestions: 4,
          score: 1,
          status: "ABANDONED",
          category: "History",
          difficulty: "HARD",
          results: [
            { questionText: "In what year did World War II end?", correctAnswer: "1945", userAnswer: "1945", isCorrect: true },
            { questionText: "Who was the first US President?", correctAnswer: "George Washington", userAnswer: "Abraham Lincoln", isCorrect: false },
            { questionText: "When did the Roman Empire fall?", correctAnswer: "476 AD", userAnswer: null, isCorrect: false },
            { questionText: "In what year was the Magna Carta signed?", correctAnswer: "1215", userAnswer: null, isCorrect: false },
          ],
        },
      ],
    },
    {
      email: "charlie@example.com",
      username: "trivia_king_99",
      password: "charlie_secret",
      bio: "I win every pub quiz.",
      sessions: [
        {
          totalQuestions: 4,
          score: 4,
          status: "COMPLETED",
          category: "Pop Culture",
          difficulty: "MEDIUM",
          results: [
            { questionText: "Who played Iron Man in the MCU?", correctAnswer: "Robert Downey Jr.", userAnswer: "Robert Downey Jr.", isCorrect: true },
            { questionText: "What year did Titanic come out?", correctAnswer: "1997", userAnswer: "1997", isCorrect: true },
            { questionText: "What is the highest-grossing film of all time?", correctAnswer: "Avatar", userAnswer: "Avatar", isCorrect: true },
            { questionText: "Who was the first Disney princess?", correctAnswer: "Snow White", userAnswer: "Snow White", isCorrect: true },
          ],
        },
        {
          totalQuestions: 2,
          score: 1,
          status: "COMPLETED",
          category: "Music",
          difficulty: "EASY",
          results: [
            { questionText: "Who is known as the King of Pop?", correctAnswer: "Michael Jackson", userAnswer: "Michael Jackson", isCorrect: true },
            { questionText: "Which band wrote 'Hey Jude'?", correctAnswer: "The Beatles", userAnswer: "The Rolling Stones", isCorrect: false },
          ],
        },
      ],
    },
    {
      email: "diana@example.com",
      username: "diana_codes",
      password: "devpassword!",
      bio: "Full-stack developer testing her geography knowledge.",
      sessions: [
        {
          totalQuestions: 3,
          score: 0,
          status: "IN_PROGRESS",
          category: "Geography",
          difficulty: "HARD",
          results: [
            { questionText: "What is the capital of Australia?", correctAnswer: "Canberra", userAnswer: "Sydney", isCorrect: false },
            { questionText: "What is the longest river in the world?", correctAnswer: "Nile", userAnswer: null, isCorrect: false },
            { questionText: "What is the smallest country in the world?", correctAnswer: "Vatican City", userAnswer: null, isCorrect: false },
          ],
        },
      ],
    },
    {
      email: "evan@example.com",
      username: "math_wizard",
      password: "numbers123",
      bio: "Numbers are my game.",
      sessions: [
        {
          totalQuestions: 5,
          score: 5,
          status: "COMPLETED",
          category: "Mathematics",
          difficulty: "EASY",
          results: [
            { questionText: "What is 2 + 2?", correctAnswer: "4", userAnswer: "4", isCorrect: true },
            { questionText: "What is 5 x 5?", correctAnswer: "25", userAnswer: "25", isCorrect: true },
            { questionText: "What is the square root of 64?", correctAnswer: "8", userAnswer: "8", isCorrect: true },
            { questionText: "What is 10 / 2?", correctAnswer: "5", userAnswer: "5", isCorrect: true },
            { questionText: "What is 3 cubed?", correctAnswer: "27", userAnswer: "27", isCorrect: true },
          ],
        },
      ],
    },
    {
      email: "fiona@example.com",
      username: "fiona_reads",
      password: "literaturelover",
      bio: "Avid reader, terrible at trivia.",
      sessions: [], // User with no sessions yet
    }
  ];

  for (const u of rawUsers) {
    const passwordHash = await Bun.password.hash(u.password);
    
    const exp = getRandomExp();

    const userData: Prisma.UserCreateInput = {
      email: u.email,
      username: u.username,
      passwordHash: passwordHash,
      bio: u.bio,
      exp: exp,
      sessions: {
        create: u.sessions?.map((session) => ({
          totalQuestions: session.totalQuestions,
          score: session.score,
          status: session.status as SessionStatus,
          category: session.category,
          difficulty: session.difficulty as Difficulty,
          results: {
            create: session.results.map((result) => ({
              questionText: result.questionText,
              correctAnswer: result.correctAnswer,
              userAnswer: result.userAnswer,
              isCorrect: result.isCorrect,
            })),
          },
        })),
      },
    };

    const createdUser = await prisma.user.create({ data: userData });
    console.log(`✅ Created user: ${createdUser.username} (EXP: ${createdUser.exp}, Sessions: ${u.sessions.length})`);
  }

  console.log("🎉 Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:");
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });